const express = require('express')
const app = express()
const handlebars = require('express-handlebars')
const bodyParser = require('body-parser')
const emailServer = require('./models/emailServer')

// Engine View
app.engine('handlebars', handlebars({ defaultLayout: 'main' }))
app.set('view engine', 'handlebars')

app.use(express.static(__dirname + '/public'))
app.use(bodyParser.urlencoded({ extended: false }))

// GIEC
var giec_main = require('./routes/giec/main')
var giec_quem_somos = require('./routes/giec/quem_somos')

app.get('/', giec_main.index)
app.get('/eventos', giec_main.eventos)
app.get('/quem-somos/comite-gestor', giec_quem_somos.comite_gestor)
app.get('/quem-somos/membros', giec_quem_somos.membros)
app.get('/quem-somos/gts', giec_quem_somos.gts)
app.get('/documentos', giec_main.documentos)
app.get('/documentos/modelos/proposta-sede-educomp', giec_main.documentos_modelo_educomp)

// Educomp 2025
var educomp_2025_home = require('./routes/simposio/2025/educomp/pt-BR/home')
var educomp_2025_chamadas = require('./routes/simposio/2025/educomp/pt-BR/chamadas')
var educomp_2025_local = require('./routes/simposio/2025/educomp/pt-BR/local')
var educomp_2025_equipes = require('./routes/simposio/2025/educomp/pt-BR/equipes')
var educomp_2025_inscricoes = require('./routes/simposio/2025/educomp/pt-BR/inscricoes')
var educomp_2025_programacao = require('./routes/simposio/2025/educomp/pt-BR/programacao')

app.get('/simposio/2025', educomp_2025_home.home)
app.get('/simposio/2025/educomp', educomp_2025_home.home)
app.get('/simposio/2025/educomp/chamadas/topicos-de-interesse', educomp_2025_chamadas.topicos_interesse)
app.get('/simposio/2025/educomp/chamadas/artigos-completos', educomp_2025_chamadas.artigos_completos)
app.get('/simposio/2025/educomp/chamadas/artigos-completos/trilha-1', educomp_2025_chamadas.criterios_trilha_1)
app.get('/simposio/2025/educomp/chamadas/artigos-completos/trilha-2', educomp_2025_chamadas.criterios_trilha_2)
app.get('/simposio/2025/educomp/chamadas/artigos-completos/trilha-3', educomp_2025_chamadas.criterios_trilha_3)
app.get('/simposio/2025/educomp/chamadas/artigos-completos/trilha-4', educomp_2025_chamadas.criterios_trilha_4)
app.get('/simposio/2025/educomp/chamadas/artigos-completos/trilha-5', educomp_2025_chamadas.criterios_trilha_5)
app.get('/simposio/2025/educomp/chamadas/ctd', educomp_2025_chamadas.ctd)
app.get('/simposio/2025/educomp/chamadas/wtd', educomp_2025_chamadas.wtd)
app.get('/simposio/2025/educomp/chamadas/minicursos', educomp_2025_chamadas.minicursos)
app.get('/simposio/2025/educomp/chamadas/mesas-tematicas', educomp_2025_chamadas.mesas_tematicas)
app.get('/simposio/2025/educomp/chamadas/laboratorio-ideias', educomp_2025_chamadas.laboratorio_ideias)
app.get('/simposio/2025/educomp/chamadas/aceitos', educomp_2025_chamadas.aceitos)
app.get('/simposio/2025/educomp/chamadas/orientacoes-apresentacao', educomp_2025_chamadas.orientacoes_apresentacao)
app.get('/simposio/2025/educomp/local/como-chegar', educomp_2025_local.como_chegar)
app.get('/simposio/2025/educomp/local/onde-hospedar', educomp_2025_local.onde_hospedar)
app.get('/simposio/2025/educomp/local/conheca-juiz-de-fora', educomp_2025_local.conheca_jf)
app.get('/simposio/2025/educomp/local/conheca-ufjf', educomp_2025_local.conheca_ufjf)
app.get('/simposio/2025/educomp/local/local-evento', educomp_2025_local.local_evento)
app.get('/simposio/2025/educomp/equipes/comissao-organizadora', educomp_2025_equipes.comissao_organizadora)
app.get('/simposio/2025/educomp/equipes/comite-programa', educomp_2025_equipes.comite_programa)
app.get('/simposio/2025/educomp/equipes/comite-diretivo', educomp_2025_equipes.comite_diretivo)
app.get('/simposio/2025/educomp/equipes/comissao-especial', educomp_2025_equipes.comissao_especial)
app.get('/simposio/2025/educomp/programacao/geral', educomp_2025_programacao.geral)
app.get('/simposio/2025/educomp/programacao/palestras-nacionais', educomp_2025_programacao.palestras_nacionais)
app.get('/simposio/2025/educomp/programacao/sessoes-tecnicas', educomp_2025_programacao.sessoes_tecnicas)
app.get('/simposio/2025/educomp/programacao/jantar', educomp_2025_programacao.jantar)
app.get('/simposio/2025/educomp/programacao/fotos', educomp_2025_programacao.fotos)

app.get('/simposio/2025/educomp/programacao/online', educomp_2025_programacao.online)

app.get('/simposio/2025/educomp/inscricoes', educomp_2025_inscricoes.inscricoes)
app.get('/simposio/2025/educomp/camisas', educomp_2025_home.camisas)

// SBC-EB 2025
var sbc_eb_2025_home = require('./routes/simposio/2025/sbc-eb/pt-BR/home')
var sbc_eb_2025_chamadas = require('./routes/simposio/2025/sbc-eb/pt-BR/chamadas')
var sbc_eb_2025_forlic = require('./routes/simposio/2025/sbc-eb/pt-BR/forlic')
var sbc_eb_2025_local = require('./routes/simposio/2025/sbc-eb/pt-BR/local')
var sbc_eb_2025_equipes = require('./routes/simposio/2025/sbc-eb/pt-BR/equipes')
var sbc_eb_2025_inscricoes = require('./routes/simposio/2025/sbc-eb/pt-BR/inscricoes')
var sbc_eb_2025_programacao = require('./routes/simposio/2025/sbc-eb/pt-BR/programacao')

app.get('/simposio/2025/sbc-eb', sbc_eb_2025_home.home)
app.get('/simposio/2025/sbc-eb/chamadas/trabalhos', sbc_eb_2025_chamadas.trabalhos)
app.get('/simposio/2025/sbc-eb/forlic', sbc_eb_2025_forlic.forlic)
app.get('/simposio/2025/sbc-eb/local/como-chegar', sbc_eb_2025_local.como_chegar)
app.get('/simposio/2025/sbc-eb/local/onde-hospedar', sbc_eb_2025_local.onde_hospedar)
app.get('/simposio/2025/sbc-eb/local/conheca-juiz-de-fora', sbc_eb_2025_local.conheca_jf)
app.get('/simposio/2025/sbc-eb/local/conheca-ufjf', sbc_eb_2025_local.conheca_ufjf)
app.get('/simposio/2025/sbc-eb/local/local-evento', sbc_eb_2025_local.local_evento)
app.get('/simposio/2025/sbc-eb/local/polo-bandeirante', sbc_eb_2025_local.polo_bandeirante)
app.get('/simposio/2025/sbc-eb/local/polo-campo-grande', sbc_eb_2025_local.polo_campo_grande)
app.get('/simposio/2025/sbc-eb/local/polo-itacoatiara', sbc_eb_2025_local.polo_itacoatiara)
app.get('/simposio/2025/sbc-eb/local/polo-salvador', sbc_eb_2025_local.polo_salvador)
app.get('/simposio/2025/sbc-eb/equipes/comissao-organizadora', sbc_eb_2025_equipes.comissao_organizadora)
app.get('/simposio/2025/sbc-eb/equipes/comite-programa', sbc_eb_2025_equipes.comite_programa)
app.get('/simposio/2025/sbc-eb/programacao/geral', sbc_eb_2025_programacao.geral)
app.get('/simposio/2025/sbc-eb/programacao/jantar', sbc_eb_2025_programacao.jantar)
app.get('/simposio/2025/sbc-eb/programacao/fotos', sbc_eb_2025_programacao.fotos)
app.get('/simposio/2025/sbc-eb/inscricoes', sbc_eb_2025_inscricoes.inscricoes)
app.get('/simposio/2025/sbc-eb/camisas', sbc_eb_2025_home.camisas)

// Educomp 2024
var educomp_2024_main = require('./routes/simposio/2024/pt-BR/main')
var educomp_2024_equipe = require('./routes/simposio/2024/pt-BR/equipe')
var educomp_2024_trabalhos = require('./routes/simposio/2024/pt-BR/trabalhos')
var educomp_2024_criterios = require('./routes/simposio/2024/pt-BR/criterios')
var educomp_2024_programacao = require('./routes/simposio/2024/pt-BR/programacao')
var educomp_2024_certificados_esquenta_1 = require('./routes/simposio/2024/pt-BR/certificado/esquenta-1')
var educomp_2024_certificados_esquenta_2 = require('./routes/simposio/2024/pt-BR/certificado/esquenta-2')
var educomp_2024_certificados_educomp = require('./routes/simposio/2024/pt-BR/certificado/educomp')

app.get('/simposio/2024', educomp_2024_main.index)
app.get('/simposio/2024/sobre', educomp_2024_main.sobre)
app.get('/simposio/2024/sobre-sbc', educomp_2024_main.sobre_sbc)
app.get('/simposio/2024/certificados', educomp_2024_main.certificados)
app.get('/simposio/2024/datas', educomp_2024_main.datas)
app.get('/simposio/2024/programacao/educomp', educomp_2024_programacao.programacao)
app.get('/simposio/2024/programacao/educomp/manha', educomp_2024_programacao.programacao_manha)
app.get('/simposio/2024/programacao/educomp/tarde', educomp_2024_programacao.programacao_tarde)
app.get('/simposio/2024/programacao/esquenta/1', educomp_2024_programacao.esquenta_1)
app.get('/simposio/2024/programacao/esquenta/2', educomp_2024_programacao.esquenta_2)
app.get('/simposio/2024/forlic', educomp_2024_main.forlic)
app.get('/simposio/2024/trabalhos/topicos-de-interesse', educomp_2024_trabalhos.topicos)
app.get('/simposio/2024/trabalhos/chamada', educomp_2024_trabalhos.chamado)
app.get('/simposio/2024/trabalhos/minicursos', educomp_2024_trabalhos.minicursos)
app.get('/simposio/2024/trabalhos/lab-ideias', educomp_2024_trabalhos.lab_ideias)
app.get('/simposio/2024/trabalhos/wtd', educomp_2024_trabalhos.wtd)
app.get('/simposio/2024/trabalhos/ctd', educomp_2024_trabalhos.ctd)
app.get('/simposio/2024/trabalhos/mesas', educomp_2024_trabalhos.mesas)
app.get('/simposio/2024/trabalhos/livros', educomp_2024_trabalhos.livros)
app.get('/simposio/2024/trabalhos/aceitos', educomp_2024_trabalhos.aceitos)
app.get('/simposio/2024/trabalhos/orientacoes', educomp_2024_trabalhos.orientacoes)
app.get('/simposio/2024/trabalhos/aceitos-orientacoes', educomp_2024_trabalhos.aceitos_orientacoes)
app.get('/simposio/2024/inscricoes', educomp_2024_main.inscricoes)
app.get('/simposio/2024/trabalhos/criterios/trilha-1', educomp_2024_criterios.artigos)
app.get('/simposio/2024/trabalhos/criterios/trilha-2', educomp_2024_criterios.trilha2)
app.get('/simposio/2024/trabalhos/criterios/trilha-3', educomp_2024_criterios.trilha3)
app.get('/simposio/2024/trabalhos/criterios/trilha-4', educomp_2024_criterios.trilha4)
app.get('/simposio/2024/trabalhos/criterios/trilha-5', educomp_2024_criterios.ensaios)
app.get('/simposio/2024/equipe/comissao-organizadora', educomp_2024_equipe.comissao_organizadora)
app.get('/simposio/2024/equipe/comite-programa', educomp_2024_equipe.comite_programa)
app.get('/simposio/2024/equipe/comite-diretivo', educomp_2024_equipe.comite_diretivo)
app.get('/simposio/2024/equipe/comissao-especial', educomp_2024_equipe.comissao_especial)
app.get('/simposio/2024/certificados/esquenta/1', educomp_2024_certificados_esquenta_1.opcoes)
app.get('/simposio/2024/certificados/esquenta/1/obter', educomp_2024_certificados_esquenta_1.certificado)
app.post('/simposio/2024/certificados/esquenta/1/obter', educomp_2024_certificados_esquenta_1.obter)
app.post('/simposio/2024/certificados/esquenta/1/obter/arquivo', educomp_2024_certificados_esquenta_1.obterArquivo)
app.get('/simposio/2024/certificados/esquenta/1/validar', educomp_2024_certificados_esquenta_1.formValidar)
app.post('/simposio/2024/certificados/esquenta/1/validar', educomp_2024_certificados_esquenta_1.validar)
app.get('/simposio/2024/certificados/esquenta/2', educomp_2024_certificados_esquenta_2.opcoes)
app.get('/simposio/2024/certificados/esquenta/2/obter', educomp_2024_certificados_esquenta_2.certificado)
app.post('/simposio/2024/certificados/esquenta/2/obter', educomp_2024_certificados_esquenta_2.obter)
app.post('/simposio/2024/certificados/esquenta/2/obter/arquivo', educomp_2024_certificados_esquenta_2.obterArquivo)
app.get('/simposio/2024/certificados/esquenta/2/validar', educomp_2024_certificados_esquenta_2.formValidar)
app.post('/simposio/2024/certificados/esquenta/2/validar', educomp_2024_certificados_esquenta_2.validar)
app.get('/simposio/2024/certificados/educomp', educomp_2024_certificados_educomp.opcoes)
app.get('/simposio/2024/certificados/educomp/obter', educomp_2024_certificados_educomp.certificado)
app.post('/simposio/2024/certificados/educomp/obter', educomp_2024_certificados_educomp.obter)
app.post('/simposio/2024/certificados/educomp/obter/arquivo', educomp_2024_certificados_educomp.obterArquivo)
app.get('/simposio/2024/certificados/educomp/validar', educomp_2024_certificados_educomp.formValidar)
app.post('/simposio/2024/certificados/educomp/validar', educomp_2024_certificados_educomp.validar)

// Educomp 2023
var educomp_2023_main = require('./routes/simposio/2023/pt-BR/main')
var educomp_2023_equipe = require('./routes/simposio/2023/pt-BR/equipe')
var educomp_2023_trabalhos = require('./routes/simposio/2023/pt-BR/trabalhos')
var educomp_2023_criterios = require('./routes/simposio/2023/pt-BR/criterios')
var educomp_2023_programacao = require('./routes/simposio/2023/pt-BR/programacao')
var educomp_2023_certificados_educomp = require('./routes/simposio/2023/pt-BR/certificado/educomp')
var educomp_2023_certificados_esquenta_1 = require('./routes/simposio/2023/pt-BR/certificado/esquenta-1')
var educomp_2023_certificados_esquenta_2 = require('./routes/simposio/2023/pt-BR/certificado/esquenta-2')

app.get('/simposio/2023', educomp_2023_main.index)
app.get('/simposio/2023/sobre', educomp_2023_main.sobre)
app.get('/simposio/2023/sobre-sbc', educomp_2023_main.sobre_sbc)
app.get('/simposio/2023/certificados', educomp_2023_main.certificados)
app.get('/simposio/2023/datas', educomp_2023_main.datas)
app.get('/simposio/2023/programacao/educomp', educomp_2023_programacao.programacao)
app.get('/simposio/2023/programacao/educomp/manha', educomp_2023_programacao.programacao_manha)
app.get('/simposio/2023/programacao/educomp/tarde', educomp_2023_programacao.programacao_tarde)
app.get('/simposio/2023/programacao/esquenta/1', educomp_2023_programacao.esquenta_1)
app.get('/simposio/2023/programacao/esquenta/2', educomp_2023_programacao.esquenta_2)
app.get('/simposio/2023/forlic', educomp_2023_main.forlic)
app.get('/simposio/2023/inscricoes', educomp_2023_main.inscricoes)
app.get('/simposio/2023/trabalhos/topicos-de-interesse', educomp_2023_trabalhos.topicos)
app.get('/simposio/2023/trabalhos/chamada', educomp_2023_trabalhos.chamado)
app.get('/simposio/2023/trabalhos/minicursos', educomp_2023_trabalhos.minicursos)
app.get('/simposio/2023/trabalhos/lab-ideias', educomp_2023_trabalhos.lab_ideias)
app.get('/simposio/2023/trabalhos/wtd', educomp_2023_trabalhos.wtd)
app.get('/simposio/2023/trabalhos/paineis', educomp_2023_trabalhos.paineis)
app.get('/simposio/2023/trabalhos/livros', educomp_2023_trabalhos.livros)
app.get('/simposio/2023/trabalhos/aceitos', educomp_2023_trabalhos.aceitos)
app.get('/simposio/2023/trabalhos/orientacoes', educomp_2023_trabalhos.orientacoes)
app.get('/simposio/2023/trabalhos/criterios/trilha-1', educomp_2023_criterios.artigos)
app.get('/simposio/2023/trabalhos/criterios/trilha-2', educomp_2023_criterios.trilha2)
app.get('/simposio/2023/trabalhos/criterios/trilha-3', educomp_2023_criterios.trilha3)
app.get('/simposio/2023/trabalhos/criterios/trilha-4', educomp_2023_criterios.trilha4)
app.get('/simposio/2023/trabalhos/criterios/trilha-5', educomp_2023_criterios.ensaios)
app.get('/simposio/2023/equipe/comissao-organizadora', educomp_2023_equipe.comissao_organizadora)
app.get('/simposio/2023/equipe/comite-programa', educomp_2023_equipe.comite_programa)
app.get('/simposio/2023/certificados/esquenta/1', educomp_2023_certificados_esquenta_1.opcoes)
app.get('/simposio/2023/certificados/esquenta/1/obter', educomp_2023_certificados_esquenta_1.certificado)
app.post('/simposio/2023/certificados/esquenta/1/obter', educomp_2023_certificados_esquenta_1.obter)
app.post('/simposio/2023/certificados/esquenta/1/obter/arquivo', educomp_2023_certificados_esquenta_1.obterArquivo)
app.get('/simposio/2023/certificados/esquenta/1/validar', educomp_2023_certificados_esquenta_1.formValidar)
app.post('/simposio/2023/certificados/esquenta/1/validar', educomp_2023_certificados_esquenta_1.validar)
app.get('/simposio/2023/certificados/esquenta/2', educomp_2023_certificados_esquenta_2.opcoes)
app.get('/simposio/2023/certificados/esquenta/2/obter', educomp_2023_certificados_esquenta_2.certificado)
app.post('/simposio/2023/certificados/esquenta/2/obter', educomp_2023_certificados_esquenta_2.obter)
app.post('/simposio/2023/certificados/esquenta/2/obter/arquivo', educomp_2023_certificados_esquenta_2.obterArquivo)
app.get('/simposio/2023/certificados/esquenta/2/validar', educomp_2023_certificados_esquenta_2.formValidar)
app.post('/simposio/2023/certificados/esquenta/2/validar', educomp_2023_certificados_esquenta_2.validar)
app.get('/simposio/2023/certificados/educomp', educomp_2023_certificados_educomp.opcoes)
app.get('/simposio/2023/certificados/educomp/obter', educomp_2023_certificados_educomp.certificado)
app.post('/simposio/2023/certificados/educomp/obter', educomp_2023_certificados_educomp.obter)
app.post('/simposio/2023/certificados/educomp/obter/arquivo', educomp_2023_certificados_educomp.obterArquivo)
app.get('/simposio/2023/certificados/educomp/validar', educomp_2023_certificados_educomp.formValidar)
app.post('/simposio/2023/certificados/educomp/validar', educomp_2023_certificados_educomp.validar)

// Educomp 2022
var educomp_2022_main = require('./routes/simposio/2022/pt-BR/main')
var educomp_2022_trabalhos = require('./routes/simposio/2022/pt-BR/trabalhos')
var educomp_2022_criterios = require('./routes/simposio/2022/pt-BR/criterios')
var educomp_2022_programacao = require('./routes/simposio/2022/pt-BR/programacao')
var educomp_2022_equipe = require('./routes/simposio/2022/pt-BR/equipe')
var educomp_2022_certificados_educomp = require('./routes/simposio/2022/pt-BR/certificado/educomp')
var educomp_2022_certificados_esquenta_1 = require('./routes/simposio/2022/pt-BR/certificado/esquenta-1')
var educomp_2022_certificados_esquenta_2 = require('./routes/simposio/2022/pt-BR/certificado/esquenta-2')

app.get('/simposio/2022', educomp_2022_main.index)
app.get('/simposio/2022/sobre', educomp_2022_main.sobre)
app.get('/simposio/2022/datas', educomp_2022_main.datas)
app.get('/simposio/2022/programacao', educomp_2022_programacao.programacao)
app.get('/simposio/2022/programacao/esquenta/1', educomp_2022_programacao.esquenta_1)
app.get('/simposio/2022/programacao/esquenta/2', educomp_2022_programacao.esquenta_2)
app.get('/simposio/2022/forlic', educomp_2022_main.forlic)
app.get('/simposio/2022/inscricoes', educomp_2022_main.inscricoes)
app.get('/simposio/2022/trabalhos/topicos-de-interesse', educomp_2022_trabalhos.topicos)
app.get('/simposio/2022/trabalhos/chamada', educomp_2022_trabalhos.chamado)
app.get('/simposio/2022/trabalhos/lab-ideias', educomp_2022_trabalhos.lab_ideias)
app.get('/simposio/2022/trabalhos/wtd', educomp_2022_trabalhos.wtd)
app.get('/simposio/2022/trabalhos/aceitos', educomp_2022_trabalhos.aceitos)
app.get('/simposio/2022/trabalhos/criterios/trilha-1', educomp_2022_criterios.artigos)
app.get('/simposio/2022/trabalhos/criterios/trilha-2', educomp_2022_criterios.trilha2)
app.get('/simposio/2022/trabalhos/criterios/trilha-3', educomp_2022_criterios.trilha3)
app.get('/simposio/2022/trabalhos/criterios/trilha-4', educomp_2022_criterios.trilha4)
app.get('/simposio/2022/trabalhos/criterios/trilha-5', educomp_2022_criterios.ensaios)
app.get('/simposio/2022/trabalhos/criterios/lab-ideias', educomp_2022_criterios.labideias)
app.get('/simposio/2022/equipe/comissao-organizadora', educomp_2022_equipe.comissao_organizadora)
app.get('/simposio/2022/equipe/comite-programa', educomp_2022_equipe.comite_programa)
app.get('/simposio/2022/certificados/esquenta/1', educomp_2022_certificados_esquenta_1.opcoes)
app.get('/simposio/2022/certificados/esquenta/1/obter', educomp_2022_certificados_esquenta_1.certificado)
app.post('/simposio/2022/certificados/esquenta/1/obter', educomp_2022_certificados_esquenta_1.obter)
app.post('/simposio/2022/certificados/esquenta/1/obter/arquivo', educomp_2022_certificados_esquenta_1.obterArquivo)
app.get('/simposio/2022/certificados/esquenta/1/validar', educomp_2022_certificados_esquenta_1.formValidar)
app.post('/simposio/2022/certificados/esquenta/1/validar', educomp_2022_certificados_esquenta_1.validar)
app.get('/simposio/2022/certificados/esquenta/2', educomp_2022_certificados_esquenta_2.opcoes)
app.get('/simposio/2022/certificados/esquenta/2/obter', educomp_2022_certificados_esquenta_2.certificado)
app.post('/simposio/2022/certificados/esquenta/2/obter', educomp_2022_certificados_esquenta_2.obter)
app.post('/simposio/2022/certificados/esquenta/2/obter/arquivo', educomp_2022_certificados_esquenta_2.obterArquivo)
app.get('/simposio/2022/certificados/esquenta/2/validar', educomp_2022_certificados_esquenta_2.formValidar)
app.post('/simposio/2022/certificados/esquenta/2/validar', educomp_2022_certificados_esquenta_2.validar)
app.get('/simposio/2022/certificados/educomp', educomp_2022_certificados_educomp.opcoes)
app.get('/simposio/2022/certificados/educomp/obter', educomp_2022_certificados_educomp.certificado)
app.post('/simposio/2022/certificados/educomp/obter', educomp_2022_certificados_educomp.obter)
app.post('/simposio/2022/certificados/educomp/obter/arquivo', educomp_2022_certificados_educomp.obterArquivo)
app.get('/simposio/2022/certificados/educomp/validar', educomp_2022_certificados_educomp.formValidar)
app.post('/simposio/2022/certificados/educomp/validar', educomp_2022_certificados_educomp.validar)

// Educomp 2021 - pt-BR
var educomp_2021_main = require('./routes/simposio/2021/pt-BR/main')
var educomp_2021_trabalhos = require('./routes/simposio/2021/pt-BR/trabalhos')
var educomp_2021_programacao = require('./routes/simposio/2021/pt-BR/programacao')
var educomp_2021_trabalhos = require('./routes/simposio/2021/pt-BR/trabalhos')
var educomp_2021_equipe = require('./routes/simposio/2021/pt-BR/equipe')
var educomp_2021_criterios = require('./routes/simposio/2021/pt-BR/criterios')
var educomp_2021_certificados = require('./routes/simposio/2021/pt-BR/certificado/esquenta-1/index')
var educomp_2021_certificados_educomp = require('./routes/simposio/2021/pt-BR/certificado/educomp/index')

app.get('/simposio/2021', educomp_2021_main.index)
app.get('/simposio/2021/sobre', educomp_2021_main.sobre)
app.get('/simposio/2021/datas', educomp_2021_main.datas)
app.get('/simposio/2021/contato', educomp_2021_main.contato)
app.get('/simposio/2021/inscricoes', educomp_2021_main.inscricoes)
app.get('/simposio/2021/forlic', educomp_2021_main.forlic)
app.get('/simposio/2021/programacao', educomp_2021_programacao.programacao)
app.get('/simposio/2021/programacao/esquenta/1', educomp_2021_programacao.esquenta_1)
app.get('/simposio/2021/programacao/esquenta/2', educomp_2021_programacao.esquenta_2)
app.get('/simposio/2021/trabalhos', educomp_2021_trabalhos.chamado)
app.get('/simposio/2021/trabalhos/aceitos', educomp_2021_trabalhos.aceitos)
app.get('/simposio/2021/topicos-de-interesse', educomp_2021_trabalhos.topicos)
app.get('/simposio/2021/equipe', educomp_2021_equipe.comissao_organizadora)
app.get('/simposio/2021/comite-programa', educomp_2021_equipe.comite_programa)
app.get('/simposio/2021/trabalhos/criterios/trilha-1/ensaios', educomp_2021_criterios.ensaios)
app.get('/simposio/2021/trabalhos/criterios/trilha-1/artigos', educomp_2021_criterios.artigos)
app.get('/simposio/2021/trabalhos/criterios/trilha-2', educomp_2021_criterios.trilha2)
app.get('/simposio/2021/trabalhos/criterios/trilha-3', educomp_2021_criterios.trilha3)
app.get('/simposio/2021/trabalhos/criterios/trilha-4', educomp_2021_criterios.trilha4)
app.get('/simposio/2021/trabalhos/criterios/lab-ideias', educomp_2021_criterios.labideias)
app.get('/simposio/2021/certificados/esquenta/1', educomp_2021_certificados.esquenta1CertificadoOpcoes)
app.get('/simposio/2021/certificados/esquenta/1/obter', educomp_2021_certificados.esquenta1Certificado)
app.post('/simposio/2021/certificados/esquenta/1/obter', educomp_2021_certificados.obterEsquenta1)
app.post('/simposio/2021/certificados/esquenta/1/obter/arquivo', educomp_2021_certificados.obterArquivoEsquenta1)
app.get('/simposio/2021/certificados/esquenta/1/validar', educomp_2021_certificados.esquenta1FormValidar)
app.post('/simposio/2021/certificados/esquenta/1/validar', educomp_2021_certificados.validarEsquenta1)
app.get('/simposio/2021/certificados/esquenta/1/resultado/:result', educomp_2021_certificados.validarEsquenta1Resultado)
app.get('/simposio/2021/certificados/educomp', educomp_2021_certificados_educomp.educompCertificadoOpcoes)
app.get('/simposio/2021/certificados/educomp/obter', educomp_2021_certificados_educomp.educompCertificado)
app.post('/simposio/2021/certificados/educomp/obter', educomp_2021_certificados_educomp.obterEducomp)
app.post('/simposio/2021/certificados/educomp/obter/arquivo', educomp_2021_certificados_educomp.obterArquivoEducomp)
app.get('/simposio/2021/certificados/educomp/validar', educomp_2021_certificados_educomp.educompFormValidar)
app.post('/simposio/2021/certificados/educomp/validar', educomp_2021_certificados_educomp.validarEducomp)

// Educomp 2021 - en-US
var educomp_2021_en_us_main = require('./routes/simposio/2021/en-US/main')

app.get('/en-US/symposium/2021/', educomp_2021_en_us_main.about)
app.get('/en-US/symposium/2021/about', educomp_2021_en_us_main.about)
app.get('/en-US/symposium/2021/topics-of-interest', educomp_2021_en_us_main.topics)
app.get('/en-US/symposium/2021/call-for-contributions', educomp_2021_en_us_main.contributors)
app.get('/en-US/symposium/2021/dates', educomp_2021_en_us_main.dates)
app.get('/en-US/symposium/2021/registrations', educomp_2021_en_us_main.incricoes)
app.get('/en-US/symposium/2021/program', educomp_2021_en_us_main.program)
app.get('/en-US/symposium/2021/team', educomp_2021_en_us_main.team)
app.get('/en-US/symposium/2021/program-committee', educomp_2021_en_us_main.committee)
app.get('/en-US/symposium/2021/contact', educomp_2021_en_us_main.contact)
app.get('/en-US/symposium/2021/forlic', educomp_2021_en_us_main.forlic)

// Envio de email
app.post('/simposio/2021/contato/email', async (req, res) => {
  emailServer.enviarEmail(req.body.email1, req.body.assunto1, req.body.mensagem1)
  res.redirect('/simposio/2021/contato')
})

// Worker do servidor
var porta = process.env.PORT || 3000
app.listen(porta, () => {
  console.log('App rodando na porta: ' + porta)
})
